# Generated by Django 5.2.9 on 2025-12-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="registration_number",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
