# Generated by Django 5.2.9 on 2025-12-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_alter_student_registration_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.RemoveField(
            model_name="student",
            name="registration_number",
        ),
    ]
