# Generated by Django 5.2.9 on 2025-12-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["title", "id"]},
        ),
    ]
