# Generated by Django 5.2.9 on 2025-12-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0004_alter_course_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ("first_name", "last_name", "id")},
        ),
    ]
